# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yj/Desktop/mytest/Client_QT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yj/Desktop/mytest/Client_QT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yj/Desktop/mytest/Client_QT/CMakeFiles /Users/yj/Desktop/mytest/Client_QT//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yj/Desktop/mytest/Client_QT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named JustTalk

# Build rule for target.
JustTalk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JustTalk
.PHONY : JustTalk

# fast build rule for target.
JustTalk/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/build
.PHONY : JustTalk/fast

#=============================================================================
# Target rules for targets named JustTalk_autogen_timestamp_deps

# Build rule for target.
JustTalk_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JustTalk_autogen_timestamp_deps
.PHONY : JustTalk_autogen_timestamp_deps

# fast build rule for target.
JustTalk_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk_autogen_timestamp_deps.dir/build.make CMakeFiles/JustTalk_autogen_timestamp_deps.dir/build
.PHONY : JustTalk_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named JustTalk_autogen

# Build rule for target.
JustTalk_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JustTalk_autogen
.PHONY : JustTalk_autogen

# fast build rule for target.
JustTalk_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk_autogen.dir/build.make CMakeFiles/JustTalk_autogen.dir/build
.PHONY : JustTalk_autogen/fast

CameraWidget.o: CameraWidget.cpp.o
.PHONY : CameraWidget.o

# target to build an object file
CameraWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/CameraWidget.cpp.o
.PHONY : CameraWidget.cpp.o

CameraWidget.i: CameraWidget.cpp.i
.PHONY : CameraWidget.i

# target to preprocess a source file
CameraWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/CameraWidget.cpp.i
.PHONY : CameraWidget.cpp.i

CameraWidget.s: CameraWidget.cpp.s
.PHONY : CameraWidget.s

# target to generate assembly for a file
CameraWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/CameraWidget.cpp.s
.PHONY : CameraWidget.cpp.s

JustTalk_autogen/mocs_compilation.o: JustTalk_autogen/mocs_compilation.cpp.o
.PHONY : JustTalk_autogen/mocs_compilation.o

# target to build an object file
JustTalk_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/JustTalk_autogen/mocs_compilation.cpp.o
.PHONY : JustTalk_autogen/mocs_compilation.cpp.o

JustTalk_autogen/mocs_compilation.i: JustTalk_autogen/mocs_compilation.cpp.i
.PHONY : JustTalk_autogen/mocs_compilation.i

# target to preprocess a source file
JustTalk_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/JustTalk_autogen/mocs_compilation.cpp.i
.PHONY : JustTalk_autogen/mocs_compilation.cpp.i

JustTalk_autogen/mocs_compilation.s: JustTalk_autogen/mocs_compilation.cpp.s
.PHONY : JustTalk_autogen/mocs_compilation.s

# target to generate assembly for a file
JustTalk_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/JustTalk_autogen/mocs_compilation.cpp.s
.PHONY : JustTalk_autogen/mocs_compilation.cpp.s

MainWindow.o: MainWindow.cpp.o
.PHONY : MainWindow.o

# target to build an object file
MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/MainWindow.cpp.o
.PHONY : MainWindow.cpp.o

MainWindow.i: MainWindow.cpp.i
.PHONY : MainWindow.i

# target to preprocess a source file
MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/MainWindow.cpp.i
.PHONY : MainWindow.cpp.i

MainWindow.s: MainWindow.cpp.s
.PHONY : MainWindow.s

# target to generate assembly for a file
MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/MainWindow.cpp.s
.PHONY : MainWindow.cpp.s

RtspServer.o: RtspServer.cpp.o
.PHONY : RtspServer.o

# target to build an object file
RtspServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/RtspServer.cpp.o
.PHONY : RtspServer.cpp.o

RtspServer.i: RtspServer.cpp.i
.PHONY : RtspServer.i

# target to preprocess a source file
RtspServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/RtspServer.cpp.i
.PHONY : RtspServer.cpp.i

RtspServer.s: RtspServer.cpp.s
.PHONY : RtspServer.s

# target to generate assembly for a file
RtspServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/RtspServer.cpp.s
.PHONY : RtspServer.cpp.s

TcpThread.o: TcpThread.cpp.o
.PHONY : TcpThread.o

# target to build an object file
TcpThread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/TcpThread.cpp.o
.PHONY : TcpThread.cpp.o

TcpThread.i: TcpThread.cpp.i
.PHONY : TcpThread.i

# target to preprocess a source file
TcpThread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/TcpThread.cpp.i
.PHONY : TcpThread.cpp.i

TcpThread.s: TcpThread.cpp.s
.PHONY : TcpThread.s

# target to generate assembly for a file
TcpThread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/TcpThread.cpp.s
.PHONY : TcpThread.cpp.s

VideoThread.o: VideoThread.cpp.o
.PHONY : VideoThread.o

# target to build an object file
VideoThread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/VideoThread.cpp.o
.PHONY : VideoThread.cpp.o

VideoThread.i: VideoThread.cpp.i
.PHONY : VideoThread.i

# target to preprocess a source file
VideoThread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/VideoThread.cpp.i
.PHONY : VideoThread.cpp.i

VideoThread.s: VideoThread.cpp.s
.PHONY : VideoThread.s

# target to generate assembly for a file
VideoThread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/VideoThread.cpp.s
.PHONY : VideoThread.cpp.s

audio_control.o: audio_control.cpp.o
.PHONY : audio_control.o

# target to build an object file
audio_control.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/audio_control.cpp.o
.PHONY : audio_control.cpp.o

audio_control.i: audio_control.cpp.i
.PHONY : audio_control.i

# target to preprocess a source file
audio_control.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/audio_control.cpp.i
.PHONY : audio_control.cpp.i

audio_control.s: audio_control.cpp.s
.PHONY : audio_control.s

# target to generate assembly for a file
audio_control.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/audio_control.cpp.s
.PHONY : audio_control.cpp.s

lobby.o: lobby.cpp.o
.PHONY : lobby.o

# target to build an object file
lobby.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/lobby.cpp.o
.PHONY : lobby.cpp.o

lobby.i: lobby.cpp.i
.PHONY : lobby.i

# target to preprocess a source file
lobby.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/lobby.cpp.i
.PHONY : lobby.cpp.i

lobby.s: lobby.cpp.s
.PHONY : lobby.s

# target to generate assembly for a file
lobby.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/lobby.cpp.s
.PHONY : lobby.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/main.cpp.s
.PHONY : main.cpp.s

meeting.o: meeting.cpp.o
.PHONY : meeting.o

# target to build an object file
meeting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/meeting.cpp.o
.PHONY : meeting.cpp.o

meeting.i: meeting.cpp.i
.PHONY : meeting.i

# target to preprocess a source file
meeting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/meeting.cpp.i
.PHONY : meeting.cpp.i

meeting.s: meeting.cpp.s
.PHONY : meeting.s

# target to generate assembly for a file
meeting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/meeting.cpp.s
.PHONY : meeting.cpp.s

pagewidget.o: pagewidget.cpp.o
.PHONY : pagewidget.o

# target to build an object file
pagewidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/pagewidget.cpp.o
.PHONY : pagewidget.cpp.o

pagewidget.i: pagewidget.cpp.i
.PHONY : pagewidget.i

# target to preprocess a source file
pagewidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/pagewidget.cpp.i
.PHONY : pagewidget.cpp.i

pagewidget.s: pagewidget.cpp.s
.PHONY : pagewidget.s

# target to generate assembly for a file
pagewidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/pagewidget.cpp.s
.PHONY : pagewidget.cpp.s

stackpage.o: stackpage.cpp.o
.PHONY : stackpage.o

# target to build an object file
stackpage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/stackpage.cpp.o
.PHONY : stackpage.cpp.o

stackpage.i: stackpage.cpp.i
.PHONY : stackpage.i

# target to preprocess a source file
stackpage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/stackpage.cpp.i
.PHONY : stackpage.cpp.i

stackpage.s: stackpage.cpp.s
.PHONY : stackpage.s

# target to generate assembly for a file
stackpage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JustTalk.dir/build.make CMakeFiles/JustTalk.dir/stackpage.cpp.s
.PHONY : stackpage.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... JustTalk_autogen"
	@echo "... JustTalk_autogen_timestamp_deps"
	@echo "... JustTalk"
	@echo "... CameraWidget.o"
	@echo "... CameraWidget.i"
	@echo "... CameraWidget.s"
	@echo "... JustTalk_autogen/mocs_compilation.o"
	@echo "... JustTalk_autogen/mocs_compilation.i"
	@echo "... JustTalk_autogen/mocs_compilation.s"
	@echo "... MainWindow.o"
	@echo "... MainWindow.i"
	@echo "... MainWindow.s"
	@echo "... RtspServer.o"
	@echo "... RtspServer.i"
	@echo "... RtspServer.s"
	@echo "... TcpThread.o"
	@echo "... TcpThread.i"
	@echo "... TcpThread.s"
	@echo "... VideoThread.o"
	@echo "... VideoThread.i"
	@echo "... VideoThread.s"
	@echo "... audio_control.o"
	@echo "... audio_control.i"
	@echo "... audio_control.s"
	@echo "... lobby.o"
	@echo "... lobby.i"
	@echo "... lobby.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... meeting.o"
	@echo "... meeting.i"
	@echo "... meeting.s"
	@echo "... pagewidget.o"
	@echo "... pagewidget.i"
	@echo "... pagewidget.s"
	@echo "... stackpage.o"
	@echo "... stackpage.i"
	@echo "... stackpage.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

